### ISSUE TITLE
Acquire domain knowledge from meta-papers on preprints

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#305]
- [x] [bioRxiv: the preprint server for biology](https://www.biorxiv.org/content/10.1101/833400v1) 
- [x] [Preprinting the COVID-19 pandemic](https://www.biorxiv.org/content/10.1101/2020.05.22.111294v2)
- [x] [On the origin of nonequivalent states: How we can talk about preprints](https://f1000research.com/articles/6-608)
- [ ] [A multi-disciplinary perspective on emergent and future innovations in peer review](https://f1000research.com/articles/6-1151/v3#d34048e4112)
- [x] [Credibility of preprints: an interdisciplinary survey of researchers](https://royalsocietypublishing.org/doi/10.1098/rsos.201520)

**Comment by giorgiosironi** [comment]
Collected in https://docs.google.com/presentation/d/1Zu-yjfoTg1brTXtfM-V6V-aTx0hdrwQatrRp-I33p0A/edit?usp=sharing
