### ISSUE TITLE
Instrument 'See more' buttons so they show up in GA

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#333]
We saw a 100% bounce rate on users visiting article pages coming from preprint review links. This appears to partially be due to GA not counting clicks on these buttons etc. as interactions:

> Bounce rate is single-page sessions divided by all sessions, or the percentage of all sessions on your site in which users viewed only a single page and triggered only a single request to the Analytics server.

From the [docs](https://support.google.com/analytics/answer/1009409?hl=en)

## ToDo

- [x] create an event for user engagement with an article page
- [x] create a trigger for the see more/less button(s)
- [x] test in GTM dev mode
- [x] verify by using utm tag on prod
- [x] check that the bounce rate is reducing
- [x] ensure @hdrury1 has GA blocked
