### ISSUE TITLE
Editorial community page has a long list of people, causes Twitter alerts

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#349]
## Problems

- [x] trigger Twitter rate limit
- [x] alerts in slack don't let us know what the error is
- [x] 18 alerts over the weekend, no response (first line support?)
- [x] UX bad: feed is below follower list, long follower list lead to scrolling required to reach feed

## Tasks

- [x] replace follower list with count
  - [x] styling
  - [x] fix the language when only 1 user following
- [x] remove Semantic UI from `renderFollowers` component
- [x] replace Promises in `renderFollowers`
  - ~consider layout~ (Nick looking into this currently)
  - ~only replace with count if we hit rate limit~
- ~remove followers entirely~
- ~don't render blank twitter user placeholders~
