### ISSUE TITLE
Show Save To List button for logged out users

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#372]
## Features

- [x] when user is logged out
  - [x] require authentication when clicking on button
  - [x] show the button to non-logged in users
  - [x] replay the command
  - [x] delete after replaying
  - [x] command is idempotent
- [x] Measurement
  - [x] Fire GA event
    - [x] breadcrumb category
    - [x] article can be deduced in GA
- [x] Remove feature flag
 
## ToDo

- [x] Taiko regression test for the logged in case

## Refactor

- ~Command is saved even if logged in~
- [x] Domain logic is duplicated across the index and finish middleware
- [x] extract anonymous redirection middleware to a named function
- ~double fold in `renderSaveArticle`~
- [x] clean up taiko test (before all, describes)

## Hour of tech-debt 

- [x] remove the `identify-user` middleware
~log in on article page doesn't redirect back to the article page~ Addressed in #381 
- [x] add a way to run a single taiko test
- [x] ~refactoring all Taiko tests to similar standards~
- [x] jest and taiko timeout durations
- [x] describe and it for respond taiko test
- [x] ~Abandoned commands remain in the session~

**Comment by giorgiosironi** [comment]
Demonstration of [how to see which article was saved](https://analytics.google.com/analytics/web/#/report/content-event-events/a167311475w233500950p219077543/_u.date00=20210121&_u.date01=20210121&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.secSegmentId=analytics.pagePath), on staging.
