### ISSUE TITLE
Implement GA consent mode to track basic data without cookies

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#379]
We can apparently implement a version of Google Analytics that doesn't require us to set cookies in the user's browser and therefore doesn't need consent.

https://support.google.com/analytics/answer/9976101?hl=en

This should hopefully give us enough of the basic data that we're looking for in the short term.

## Definition of Done

- [x] GTM and GA should be loaded by default
- [x] no `__ga` cookie should be created by default
- [x] upon consent, cookies get created
- [ ] we can track page visits from unconsenting users
- [ ] we can track in-page events from unconsenting users

## Options

- [ ] stick with current code (no functionality improvement)
- [ ] research GA in consent mode (timebox)
- [ ] experiment with turning off `storage` in `gtag()`
  - [ ] can this be turned on again after consent?
- [ ] investigate alternatives to GA
  - [ ] fathom
  - [ ] consider tools that could analyse our logs
- [ ] count pageviews using server-side events
- [ ] make Sciety difficult or impossible to use without consent

## Tasks

- [ ] insert new (basic) code
  - [ ] work out what to do differently for `<noscript>` (if anything)
  - [ ] check to see whether we need to insert `wait_for_update`
- [ ] give consent with gtag API if the user so indicates
- [ ] is there memory of consent across pages, or do we need to do something to make that happen?
- [ ] try to determine if consent mode is GDPR compliant

## Refactoring
- [ ] make gtm code readable

## Tech debt
- [ ] Speed up build

**Comment by will-byrne** [comment]
https://www.iubenda.com/en/help/27137-google-consent-mode

**Comment by giorgiosironi** [comment]
Current status on staging is:

- after consent, page views and events are tracked as before
- before consent, neither show up (despite the recording in the GTM extension showing them)
- 
This is consistent within the Real Time and Behavior reports for both page views and events.

**Comment by giorgiosironi** [comment]
Confirming GA can be used without cookies somehow and page counts should be respected (but not user or session counts): https://helgeklein.com/blog/2020/06/google-analytics-cookieless-tracking-without-gdpr-consent/

**Comment by giorgiosironi** [comment]
https://www.simoahava.com/analytics/consent-mode-google-tags/ states:

> However, these cookieless hits are sent to Google Analytics with a new gcs parameter, which includes the consent status of the hit. The cookieless hits are thus identified by Google Analytics and _for now_ are not collected or exposed in reporting at all.
> Most likely Google will at some point build actionable data out of the cookieless data set as well, perhaps after applying extensive modelling to make it align with the data that was collected with storage consent.

but also:

> The main difference between consent mode and using the storage field to block analytics tags from having access to `storage` is that consent mode will not surface the data in reports whereas setting `storage` to `none` will.
