### ISSUE TITLE
Update Zapier to watch for medRxiv reviews from eLife

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#391]
The "zap" in [Zapier](https://zapier.com/app/login) monitors the [Editorial Team's Tracking Spreadsheet ](https://docs.google.com/spreadsheets/d/1oy8TIwsedSYdy6n3_SFuqUcJ4Ljeg7tXnTS6q2CsNI8/edit#gid=553544812 ).

The `LEGACY` sheet used by the existing zap doesn't have any medrxiv content. Therefore migration should occur once we can move to the new sheet.

## Readying

- [x] coordinate with Editorial to confirm which sheet they are using and how they are using it
- [x] are there consistent, machine readable columns that can be used for the zap?
- [x] what should the new zaps do?

## Tasks
- [x] **Last task:** let Fiona in the Editorial Team know once done as she wants to remove the redundant columns

## Tech debt

- [x] where to store sciety credentials
  - SASS password manager
  - mozilla SOPS
  - ~private repo~

**Comment by hdrury1** [comment]
The Editorial team are using two sheets: `Preprint Review (FB)` and `Preprint Review (new)`.

We need Zaps that look at both sheets, update #sciety-content and email corresponding authors when reviews are posted to bioRxiv/medRxiv

**Comment by BlueReZZ** [comment]
I added a task to do at the end (let Fiona know) as she was keen to tidy up the spreadsheet once we're done here

**Comment by erkannt** [comment]
Tried working on this. We ran into multiple questions and are postponing until we can work with domain expert.

- column name in new only refers to 'biorxiv'
- posted by filter looks for 'yes' but sheet uses 'AC'
- are rows moved before or after filling them out? could trigger zap twice?
