### ISSUE TITLE
Ensure preLights dev team have everything they need for new feed development

### ISSUE THREAD

**Issue by BlueReZZ** [sciety/sciety#470]
Julian from the preLights development team updated us with the following:

## Feed Update / Specification

- The RSS feed will follow the current Wordpress feed conventions for posts, with the following changes:
- The feed will be protected by a key on the URL, the feed URL will be `{prelights sit url}/feed/sciety/?key={key inserted here}`
- Calls to the feed will, by default, contain all preLights posts and preList post types, we do however recommend that the following 'hours' restriction is used (see below).
- The feed can be restricted for only posts created in the last x hours via a URL argument 'hours' for example: `{prelights sit url}/feed/sciety/?key={key inserted here}&hours=24`
- The feed can be restricted to a single post by supplying a doi as a 'doi' URL argument, for example: `{prelights sit url}/feed/sciety/?key={key inserted here}&doi=10.1242/prelights.25121`
- Additional fields will be added to the feed as follows:
  - The type of the post (preLight or preList). 
  - A new field called 'onelinesummary' which contains our one line summary.
  - The doi of the preLights post itself (if available, dois are not allocated until 7 days after publication).  This is not to be confused with the doi of the preprint being discussed in the preLight post (which is available in the <preprints> nodes if held).
  - For each preprint referenced/discussed in the post:
    - The original URL of the preprint.
    - The doi of the preprint, if this is known.
    - Whether the author of the preprint has responded to the preLight post (i.e. if the preLight post contains an 'author response' section for this specific preprint).
 
Please let us know if there are any additional fields you would like included.  The best reference is a preLights post, although we do hold some additional behind the scenes data it is unlikely to be useful for your feed consumption.

## Testing

Testing will be completed on our staging server, the staging server contains a mixture of real and test data (as it is cloned from the live site at intervals). The staging server is access controlled, we will require either of the following details to enable your routes to access the system:
- IP addresses of the servers / systems making the calls.
- User agents of the scripts making the calls.

## Tasks
-  ~Supply the preLights team with IP addresses of the servers / systems making the calls~
- [x] Supply the preLights team with User agents of the scripts making the calls.
- [x] Check the proposed specification above
- [x] Let the preLights team know if there are additional fields that would be useful
- [x] Follow up on Tuesday email from Julian
- [x] Check staging site
  - [x] Check finding out about all the reviews
  - [x] Check finding out full text of individual reviews
- [x] Look at email with the mob

**Comment by giorgiosironi** [comment]
Example:
```
scripts/find-reviews-from-crossref-via-biorxiv.ts:        'User-Agent': 'Sciety (http://sciety.org; mailto:team@sciety.org)',
```

**Comment by thewilkybarkid** [comment]
- Not all reviews have DOIs. For those that don't, there doesn't seem to be a suitable identifier available to use instead.

**Comment by giorgiosironi** [comment]
The `author` field seems to be inconsistently populated with some hardcoded values (preLights Technical Team) and we are unsure whether it could be shown.

The `content:encoded` field seems to include headings as part of the text without any additional markup inside the CDATA. This creates an ambiguity on whether the text is part of a heading or the body:       
```   
     <![CDATA[Background During very early stages of zebrafish embryonic development, before the mid-blastula transition (MBT)...
```

**Comment by giorgiosironi** [comment]
Provided feedback and waiting to hear back before closing.

**Comment by giorgiosironi** [comment]
More feedback:

> We only have DOIs allocated 7 days after publication (and only for the live system). In the absence of a DOI, the guid's p value can be used

Our take is to ignore items without DOIs in the ingestion script, only adding them when there is a DOI available.

> For biorxiv you can safely follow the URL to derive a DOI - its the same process as we use (just it can take up to 24 hours for the DOI to appear on prelights).

Not sure if they mean loading the URL or parsing it, but if we wait enough days the DOI is available.

> The author field contains the name of the preLighter (or contributor) who has generated the post, using the display format they have asked for for their name. The 'preLights Technical Team' is not hard coded, it just happens to be that on staging our admin users raises or clones posts and therefore is assigned as the author.

Seems only a problem in staging.

On the `content:encoded`, open question:

> This is an excerpt of the post, at the moment the excerpt process strips out markup and therefore issues like the above can occur. We will review and see if this can be optimised, how are you intending to use this block of data?  If we include markup would that cause issues?

Complex question as it depends on the markup, but will answer to give us a sample or to eventually include as we can always strip markup out, but not add it if missing.

**Comment by hdrury1** [comment]
Latest feedback:

> I hope you are having a good week, We've updated the feed to include a number of permitted tags in the content node. it should be noted that as the content is an extract of the full copy, not the full content, you may end up with some tags with opening elements but no closing element - something to be aware of when using this element. Let us know how you get on.
