### ISSUE TITLE
Colour accessibility

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#531]
## Tasks
- [x] understand the usage intent for the colours found on the activity page
- [x] de dupe / rationalise number of colours if possible (not currently possible)
- [x] refactor sass variables based on understanding of usage:
  - [x] `$colour-activity-page-text` becomes `$colour-text-primary`
  - [x] `$colour-activity-feed-teal-one` becomes `$colour-brand`
  - [x] Create new variable `$colour-text-secondary: $colour-brand`
  - [x] Text uses of old `$colour-activity-feed-teal-one` should use `$colour-text-secondary`
  - [x] Non-text uses of old `$colour-activity-feed-teal-one` should use `$colour-brand` 
  - [x] `$colour-activity-feed-toggle` becomes `$colour-accent`
  - [x] `$colour-activity-page-background` becomes `$colour-page-background`
  - [x] `$colour-activity-feed-responses-background` becomes `$colour-component-background`
  - [x] `$colour-article-border` becomes `$colour-furniture`
  - [x] `$colour-overlay` becomes `$colour-avatar-overlay`
  - [x] Remove `$colour-activity-feed-teal-two`, and remove the borders of the responses buttons (the only place that it's used).
- [x] First pass: check accessibility of relevant background / foreground colour combinations using https://contrastchecker.com/ (See results attached https://github.com/sciety/sciety/issues/531#issuecomment-790556171)
  - [x] against a background of $colour-page-background
    - [x] check $colour-text-primary
    - [x] check $colour-text-secondary
    - [x] check $colour-accent
  - [x] against a background of $colour-component-background
    - [x] check $colour-text-primary
    - [x] check $colour-text-secondary
    - [x] check $colour-accent
  - [x] against a background of $colour-brand
    - [x] check white
  - [x] against a white background
    - [x] check $colour-text-primary
    - [x] check $colour-text-secondary
    - [x] check $colour-accent
  - [x] against a background of $colour-accent:
    - [x] check white
- [x] make adjustments to improve colour contrasts where necessary.
  - [x] darken $colour-text-secondary to rgb(75, 96, 106) to pass at small font sizes
  - [x] darken $colour-text-primary to rgb(52, 67, 74) to complement secondary text colour change
  - [x] darken $colour-accent to rgb(206, 72, 26) to enable pass against white. **Note that this does not pass against $colour-page-background nor $colour-component-background so do not it in these combinations**
- [x] Second pass: rerun checks as a batch with new colours & attach generated PDF to this ticket.

**Comment by will-byrne** [comment]
[my-wcag-color-samples.pdf](https://github.com/sciety/sciety/files/6083383/my-wcag-color-samples.pdf)
Accessibility results (in reverse order)

**Comment by erkannt** [comment]
Accessibility results for `primary`, `secondary` and `accent` against `FFFFFF`, `page-background` and `component-background` (results go from bottom to top).

https://contrastchecker.com/?swatch_session=1614944872937
[my-wcag-color-samples.pdf](https://github.com/sciety/sciety/files/6090448/my-wcag-color-samples.pdf)
