### ISSUE TITLE
Combine /terms and /privacy into one page

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#569]
- [x] Combine content from /terms and /privacy and address into one page
- [x] add other footer info to this page
- [x] add `Sciety is operated by a team based within eLife Sciences Publications Limited. It is steered by all of its communities, readers and authors.` to legal page
- [x] add link to single legal page to footer
- [x] remove superfluous info from footer
- [x] remove unused pages
- [x] remove unused SASS

## Refactoring
- [x] dedupe redirects

## Questions
- [x] Does the copyright date in the footer need to change? (Currently we have "2020", in comparison eLife site says "2021"). See https://github.com/sciety/sciety/issues/569#issuecomment-800373635
- [x] Current footer has creative commons license note, new design doesn't. Is this okay? See https://github.com/sciety/sciety/issues/569#issuecomment-800373635
- [x] What is mandatory to have on every page? Any of it? 😅 See https://github.com/sciety/sciety/issues/569#issuecomment-800373635

**Comment by BlueReZZ** [comment]
> Does the copyright date in the footer need to change? (Currently we have "2020", in comparison eLife site says "2021").

My understand was always that you had a range that stated the first time a work was claimed by the rights holder up to the time the claim was left. However, most people seem to just put the current year for web content so I'm happy to follow eLife's example.

> Current footer has creative commons license note, new design doesn't. Is this okay?

If this is in the legal page then it doesn't have to be on the footer. The licencing of content on Sciety needs a bit of reading as you have to check each group's policy before re-using so having to navigate to the legal page for the detail on that shouldn't be an issue

> What is mandatory to have on every page? Any of it? sweat_smile

The copyright notice is the minimum as long as it is reasonable easy for someone to find all the other information and the link to the legal information page satisfies that

**Comment by davidcmoulton** [comment]
From `/legal`:
"Unless otherwise indicated the Editorial Community names, logos and trademarks are owned by their respective owners and not by eLife or its licensors. The article content is created by the authors stated on the article page and is not owned by eLife or its licensors, and is subject to the licence terms shown against it. Evaluation content is created by the Editorial Community named alongside the evaluation content and is not owned by eLife or its licensors, and is subject to the licence terms shown on the Editorial Community's page." 

It doesn't mention CC, is this sufficient to enable us to remove the licence statement from the footer?

**Comment by BlueReZZ** [comment]
> It doesn't mention CC, is this sufficient to enable us to remove the licence statement from the footer?

Answered and updated with commit https://github.com/sciety/sciety/commit/d99b07d5c8ba7bfe725596edbae645d89aa2b40b
