### ISSUE TITLE
Organisational authors in article meta page

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#631]
The article meta page omits organisational authors.

## Steps to reproduce:
1. Search for 10.1101/2021.04.06.438687
2. Note the first author is "SEQC2 Oncopanel Sequencing Working Group"
3. Click on the article title
4. Click on the article tab
5. Note the first author is "Yifan Zhang", and that **"SEQC2 Oncopanel Sequencing Working Group"** is missing

## Fix
- [x] Identify problem
  `<organization>` element within `<contributors>` is ignored
- [x] Write unit test
- [x] Process `<organization>` element 
- [x] Log unexpected elements with `contributor-role="author"`

## Refactoring
- [x] Extract respective author tags processing logic as functions
- [x] Agree on how to move the fallbacks to the renderers (e.g. `Either`s or somthing else)

## Tech Debt
- [ ] parse/fetch crossref article
  - [ ] make all parse getters return options
  - [ ] remove throws
  - [ ] make code functional
